### ISSUE TITLE
Generating a CSV for simulation results

### ISSUE THREAD

**Issue by gmarupilla** [biosimulators/Biosimulators_tellurium#2]
![image](https://user-images.githubusercontent.com/53095348/94600585-135e5f80-0260-11eb-9399-08f5ee0ce7f1.png)

Above Image was taken from [here](https://tellurium.readthedocs.io/en/latest/notebooks.html#simulation-options)

Currently, we're just exporting pdf files for visualisation of final simulations not the CSV data of timepoints and all variables for those time-points. From the above photo taken from the docs, it seems it's not a hassle to have the simulator export CSV just like VCell and COPASI do, this way we would be able to generate interactive visualisations for tellurium simulations as well and make it consistent across all the simulators.

@jonrkarr @bilalshaikh42 your thoughts?

**Comment by jonrkarr** [comment]
I'm not sure I understand your question.

We've discussed the need to record the raw results (in CSV format) many times. The raw results are essential for visualize (and numerical) analysis of simulation results. The containerized simulation tools must record simulation results in CSV format at the same relative location as the SED-ML file within the COMBINE/OMEX archive. In particular, the containers must record the outputs specified in the SED-ML file(s) in the COMBINE/OMEX archive. This is described in the documentation for the containers. The test utility verifies that simulation tools record the specified outputs in CSV format. The tellurium and BioNetGen containers already do this.

**Comment by gmarupilla** [comment]
After running a few simulations with all known OMEX archives, I learned that Tellurium generates CSV results (Previously, I assumed wrong). Yes, we did discuss the raw result structure, and I'm evident about that as well.

But when the SED-ML has the `<listOfOutputs>` in the condition of `Plot2D` or `Plot3D` only, then CSV result file(s) are not getting generated, which should not be the case. 

PFA for OMEX archive to reproduce the simulation.
[BIOMD0000000689.omex.zip](https://github.com/biosimulators/Biosimulators_tellurium/files/5302061/BIOMD0000000689.omex.zip)

**Comment by jonrkarr** [comment]
A `report` output has to be explicitly stated in the SED-ML document. This is what instruct tellurium (and other tools) to generate CSV files.

**Comment by gmarupilla** [comment]
Do we need to generate these visualization pdf's like tellurium does, in COPASI as well?

**Comment by jonrkarr** [comment]
The short answer is no. The containers don't need to generate PDFs.

The 2d and 3d plots are part of the SED-ML standard.

At least for now, we are only requiring containers to support a subset of the SED-ML standard
- Single simulation tasks
- Recording individual simulation predictions (e.g., species concentrations)
- Reports (CSV) files

We don't need PDFs of plots because this overlaps with the functionality of our own visualizations. Our own visualizations are more flexible.

**Comment by jonrkarr** [comment]
I've started to create documentation on building containerized simulation tools here: https://biosimulators.org/help

**Comment by gmarupilla** [comment]
Will makes minor changes https://github.com/biosimulators/Biosimulators_COPASI/issues/35
